services:
  backend:
    build: .
    ports:
      - '4000:80'
    links:
      - 'mongo:database'
    environment:
      MONGO_URI: mongodb://database/meeorder

  mongo:
    image: mongo
    ports:
      - '27017:27017'
