name: NestJS build, lint and test CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build

  build-image:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        run: |
          echo $CR_PAT | docker login ghcr.io -u meeorder --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/meeorder/meeorder-backend-test:${{github.sha}}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build-image
    services:
      db:
        image: mongo:6
        ports:
          - 27017:27017
        options: --network default
      backend:
        image: ghcr.io/meeorder/meeorder-backend-test:${{github.sha}}
        credentials:
          username: meeorder
          password: ${{ secrets.CR_PAT }}
        ports:
          - 4000:80
        options: --network default
        env:
          MONGO_URI: mongodb://db:27017
          MONGO_DB_NAME: meeorder
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run test:cucumber
        env:
          BASE_URL: http://localhost:4000
          MONGO_URI: mongodb://localhost:27017
          MONGO_DB_NAME: meeorder
