name: NestJS build, lint and test CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: isbang/compose-action@v1.5.0
        with:
          compose-file: './docker-compose.yml'
          services: |
            mongo
            backend

      - name: Curl Test
        run: curl -X GET http://localhost:4000/api/v1/health/ping
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run test:cucumber
        env:
          BASE_URL: http://localhost:4000
          MONGO_URI: mongodb://localhost:27017
          MONGO_DB_NAME: meeorder
