name: Releaseing Docker (Dev)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: yarn install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
      - name: Build Backend
        run: yarn build
      - name: Start Backend Server
        run: yarn start:pm2
        env:
          MONGO_URI: mongodb://127.0.0.1:27017
          MONGO_DB_NAME: meeorder
          PORT: 4000
      - name: Waiting Service
        run: chmod +x ./.github/wait.sh && ./.github/wait.sh ${{env.TEST_URL}}
        env:
          TEST_URL: http://127.0.0.1:4000/health/ping
      - name: Run Cucumber Test
        run: yarn test:cucumber
        env:
          BASE_URL: http://127.0.0.1:4000
          MONGO_URI: mongodb://127.0.0.1:27017
          MONGO_DB_NAME: meeorder
  docker:
    runs-on: ubuntu-latest
    needs:
      - 'build'
      - 'test'
      - 'e2e'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        run: |
          echo $CR_PAT | docker login ghcr.io -u meeorder --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/meeorder/meeorder-backend-dev:latest
