name: Meeorder-Backend Self Host

on:
  push:
    branches:
      - develop
      - self-host-test
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: npm install, build, and test
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
          cp /home/vjumpkung/meeorder-backend/.env .
          pnpm run stop:pm2
          pnpm run start:pm2
