name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
      - name: Generate Swaggon json
        run: pnpm run test:e2e
        env:
          BASE_URL: http://127.0.0.1:4000
          MONGO_URI: mongodb://127.0.0.1:27017
          MONGO_DB_NAME: meeorder
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger.json
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
