name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - test-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run start
      - name: Swagger ui action
        id: swagger-ui-action
        uses: pjoc-team/swagger-ui-action@v0.0.2
        env:
          SWAGGER_JSON_URL: https://meeorder.github.io/meeorder-backend/apis/swagger.json
        with:
          dir: './'
          pattern: '*.json'
          debug: 'true'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
        env:
          SWAGGER_JSON_URL: https://meeorder.github.io/meeorder-backend/apis/swagger-spec.json
